site_name: Pawned passwords
nav:
  - 'index.md'      
  - 'bd-guidelines.md'

theme:
  name: material
  language: fr
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    # Integration de la table des matières dans le menu gauche
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration
    - toc.integrate
    - toc.follow

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
          - name: php
            lang: php
            options:
                startinline: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:       
      toc_depth: '2-3'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
# - extra-sass
# - with-pdf
  - search
  - include-markdown
  - toc-md:
      toc_page_title: Table des matières
      header_level: 2